application: block-scheduler
version: 4
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /favicon\.ico
  static_files: images/favicon.ico
  upload: static/favicon.ico
  mime_type: "image/png"
- url: /css
  static_dir: css
  mime_type: "text/css"
- url: /images
  static_dir: images
  mime_type: "image/jpg"
- url: /.*
  script: hello.app

libraries:
- name: jinja2
  version: latest